name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend
        run: |
          cd backend
          npm ci
      - name: Install frontend
        run: |
          cd frontend
          npm ci
      - name: Lint and test backend
        run: |
          cd backend
          npm test -- --ci
      - name: Build frontend
        run: |
          cd frontend
          npm run build





